spring.datasource.url=jdbc:mysql://localhost:3306/zoo_fantastico
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# SQL Initialization
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.sql.init.data-locations=classpath:sql/schema.sql,classpath:sql/data.sql
spring.sql.init.continue-on-error=true

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.root=INFO
logging.level.com.javeriana.zoo_fantastico=DEBUG
logging.level.org.springframework.web=DEBUG